version: '3.8'

services:
  # Laravelアプリケーションのコンテナ
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - './:/var/www/html'  # src ではなくプロジェクトルートをマウント
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - PHP_EXTENSIONS=pdo_mysql
    ports:
      - 80:80

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["composer", "install"]

  # Nginxサーバーのコンテナ
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./Mitetene:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # MariaDBのコンテナ
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
  
  #node:
    #image: node:18  # Node.jsのイメージを指定
    #volumes:
      #- './:/var/www/html'  # Laravelプロジェクトのボリュームをマウント
    #working_dir: /var/www/html

# ボリュームの定義
volumes:
  db_data:

# ネットワークの定義
networks:
  laravel_network:
    driver: bridge
